layout_spectrum: 0.9941468683768543
typography_spectrum: 0.6560272449604466
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.9364611557576031
  lightness: 0.12793378272020065
  saturation: 0.46602308935070835
  rhythmicContrast: 0.17331537517036616
github: true
name: 'I''m a Front End Developer '
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: 'tablespoon '
    id: fe0a8f20-bdfa-4ad1-9169-655880244d54
    type: content
  - name: bank of internet
    id: ac52c7cb-4613-4840-b62b-fa3bda89da26
    type: content
  - name: resume
    id: 5214f9dc-de9f-4f5a-b809-fbfa08457920
    type: content
title: Trang B. Salinas
content: []
description: ''
purpose: []
